version: 2.1
jobs: 
  test:
    description: Run tests
    steps:
      - checkout
      - run:
          name: Test Runner
          command: make test
workflows:
  "Circle CI Tests":
    jobs:
      - test